spring:
  application:
    name: code-synthesis-tool
  data:
    mongodb:
      uri: mongodb+srv://encora:hdvM4jJEuQPppetW@misti.ymgru.mongodb.net/test?retryWrites=true&w=majority&appName=misti

logging:
  level:
    root: DEBUG
    org:
      mongodb:
        driver: INFO
    sun:
      rmi: ERROR
    javax:
      management:
        remote:
          rmi: ERROR