spring:
  application:
    name: code-synthesis-tool
  data:
    mongodb:
      uri: mongodb+srv://encora:hdvM4jJEuQPppetW@misti.ymgru.mongodb.net/test?retryWrites=true&w=majority&appName=misti

jwt:
  token-expiration-time: 3600000
  refresh-expiration-time: 7200000


logging:
  level:
    root: DEBUG
    org:
      springframework:
        web:
          reactive: DEBUG
        security: DEBUG
      mongodb:
        driver: INFO
    sun:
      rmi: ERROR
    javax:
      management:
        remote:
          rmi: ERROR

# Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /v3/api-docs

  # Specify the path of the Swagger UI
  swagger-ui:
    path: /swagger-ui.html

  # Enable or disable Swagger UI
    enabled: true
